"""Exercise daily ideas in bundled Python using isolated data and labelled fixture output."""

import argparse
import hashlib
import io
import json
from pathlib import Path
import tempfile
from uuid import uuid4
from PIL import Image
from verify_content_memory_runtime import runtime, call, ROOT


def status(client):
    return call(client, "GET", "/ideas/status", params={"timezone": "Asia/Jakarta"})


def main(app, report):
    checks = []
    resources = app.resolve() / "Contents/Resources"
    with tempfile.TemporaryDirectory(prefix="jdh-daily-ideas-qa-") as temporary:
        directory = Path(temporary)
        with runtime(resources, directory) as client:
            assert status(client)["onboarding"]
            project = call(
                client,
                "POST",
                "/projects",
                json={
                    "name": "Counter lesson",
                    "script": "State updates a SwiftUI counter.",
                    "language": "en",
                },
            )
            pid = project["id"]
            picture = io.BytesIO()
            Image.new("RGB", (40, 40), "#667788").save(picture, format="PNG")
            imported = call(
                client,
                "POST",
                f"/projects/{pid}/media",
                files={"file": ("qa.png", picture.getvalue(), "image/png")},
            )
            aid = imported["asset"]["id"]
            project_before = call(client, "GET", f"/projects/{pid}")
            media_before = hashlib.sha256(
                client.get(f"/api/projects/{pid}/media/{aid}").content
            ).hexdigest()
            catalog = call(client, "GET", "/memory")["catalog"]
            call(
                client,
                "POST",
                "/memory/references",
                json={"revision": catalog["revision"], "project_ids": [pid]},
            )
            current = status(client)
            call(
                client,
                "PUT",
                "/ideas/preferences",
                json={
                    "timezone": "Asia/Jakarta",
                    "revision": current["settings_revision"],
                    "preferences": {**current["preferences"], "mode": "manual"},
                },
            )
            assert not status(client)["auto_due"]
            checks += [
                "empty catalogue onboarding",
                "selected local reference",
                "manual mode",
            ]
            # This client emulates the transport, not the language model.
            doc = str(uuid4())
            code = call(client, "POST", "/ai/pair", json={})["code"]
            origin = str(client.base_url).rstrip("/")
            headers = {"Origin": origin}
            paired = client.post(
                "/nano/api/pair",
                headers=headers,
                json={"code": code, "document_id": doc},
            )
            paired.raise_for_status()
            headers["X-JDH-Nano"] = paired.json()["token"]

            def poll():
                response = client.post(
                    "/nano/api/poll",
                    headers=headers,
                    json={
                        "document_id": doc,
                        "english": "available",
                        "indonesian": "unavailable",
                    },
                )
                response.raise_for_status()
                return response.json()

            poll()
            rid = str(uuid4())
            body = {"id": rid, "timezone": "Asia/Jakarta", "automatic": False}
            first = call(client, "POST", "/ideas/generate", json=body)
            assert first["active_id"] == rid
            assert (
                call(client, "POST", "/ideas/generate", json=body)["active_id"] == rid
            )
            job = poll()["job"]
            assert job["operation"] == "ideas"
            assert (
                json.loads(job["input"])["history"]["references"][0]["project_id"]
                == pid
            )
            assert len(job["input"]) < 12000
            ideas = [
                {
                    "category": category,
                    "title": f"QA FIXTURE — {category}",
                    "hook": f"Fixture hook for {category}.",
                    "concept": "Transport test only; not generated by Nano.",
                    "reason": "Selected local lesson.",
                    "difference": "Show a reset action.",
                    "estimated_seconds": 30,
                    "media_needs": ["A new screen recording"],
                    "source_project_ids": [pid],
                }
                for category in ["series", "new_angle", "experiment"]
            ]
            result = client.post(
                "/nano/api/result",
                headers=headers,
                json={
                    "document_id": doc,
                    "id": rid,
                    "status": "completed",
                    "ideas": ideas,
                },
            )
            result.raise_for_status()
            cached = status(client)
            assert len(cached["batch"]["cards"]) == 3 and not cached["stale"]
            card = cached["batch"]["cards"][0]
            call(
                client,
                "PUT",
                f"/ideas/cards/{card['id']}/feedback",
                json={
                    "timezone": "Asia/Jakarta",
                    "verdict": "saved",
                    "reason": "Fixture follow-up",
                },
            )
            skipped = cached["batch"]["cards"][1]
            call(
                client,
                "PUT",
                f"/ideas/cards/{skipped['id']}/feedback",
                json={
                    "timezone": "Asia/Jakarta",
                    "verdict": "skipped",
                    "reason": "Too similar",
                },
            )
            checks += [
                "idempotent request",
                "bounded curated context",
                "validated three-card fixture",
                "save and skip feedback",
            ]
        with runtime(resources, directory) as client:
            restored = status(client)
            assert restored["batch"] == cached["batch"]
            assert len(restored["feedback"]) == 2
            assert not restored[
                "can_generate"
            ]  # Companion is deliberately absent after restart.
            assert not call(
                client,
                "POST",
                "/ideas/generate",
                json={
                    "id": str(uuid4()),
                    "timezone": "Asia/Jakarta",
                    "automatic": True,
                },
            )["active_id"]
            assert call(
                client, "GET", "/ideas/status", params={"timezone": "Pacific/Honolulu"}
            )["stale"]
            checks += [
                "cache and feedback survive bundled process restart",
                "offline cache without automatic retry",
                "timezone invalidates freshness",
            ]
            catalog = call(client, "GET", "/memory")["catalog"]
            call(
                client,
                "POST",
                f"/memory/references/{pid}/forget",
                json={"revision": catalog["revision"]},
            )
            invalidated = status(client)
            assert invalidated["batch"] is None and invalidated["feedback"] == []
            assert call(client, "GET", f"/projects/{pid}") == project_before
            assert (
                hashlib.sha256(
                    client.get(f"/api/projects/{pid}/media/{aid}").content
                ).hexdigest()
                == media_before
            )
            checks += [
                "forget purges cache and saved feedback",
                "project and actual PNG unchanged",
                "clean EOF shutdown",
            ]
    result = {
        "app": str(app),
        "version": "0.2.4",
        "isolated_data": True,
        "real_nano_inference": False,
        "fixture_label": "QA FIXTURE",
        "checks": checks,
        "passed": True,
    }
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text(json.dumps(result, indent=2) + "\n")
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--app", type=Path, default=ROOT / "dist/JDH Shorts Studio.app")
    parser.add_argument(
        "--report", type=Path, default=ROOT / "docs/qa/daily-ideas-runtime.json"
    )
    args = parser.parse_args()
    main(args.app, args.report)
